-- ==============================================================================
-- 01. SEED ALL 10 PORTFOLIO PROJECTS
-- ==============================================================================

insert into public.projects (id, title, slug, category, platform, technologies, short_description, description, role, features, brainstorming, hero_image, gallery, live_url, featured, results_highlights, order_index) values
  (
    'proj-1',
    'Aura Apparel Shopify Store',
    'aura-apparel-shopify-store',
    'SHOPIFY',
    'Shopify',
    array['Shopify', 'PageFly', 'Liquid', 'JavaScript', 'Custom CSS'],
    'Modern fashion e-commerce experience focused on product discovery, responsive layouts, and custom Shopify section development.',
    'A complete Shopify e-commerce solution designed for a contemporary apparel brand. Built using custom Shopify sections alongside PageFly page builder for high-conversion product landing pages. Features seamless mobile shopping, fast AJAX cart drawer, custom color swatch filters, and optimized checkout flow.',
    'Lead Shopify Developer',
    array['Custom Shopify Liquid theme section development', 'PageFly page builder landing page optimization', 'Dynamic AJAX side-cart drawer & mini-cart', 'Custom product variant color swatch selector', 'Mobile-first responsive layout & mega menu', 'Integrated product reviews & trust badge signals'],
    '[{"title":"Project Goal","content":"Transform the brand''s online storefront into a high-speed, mobile-optimized shopping experience with custom product presentation flexibility."},{"title":"Design & UX Considerations","content":"Prioritized visual clarity and minimal click-to-buy friction. Used bold visual hierarchy, crisp typography, and touch-friendly UI elements."},{"title":"Development Approach","content":"Combined Shopify''s native Liquid templating engine with custom CSS and modular JavaScript for interactive filters without heavy third-party app bloat."},{"title":"Challenges & Solutions","content":"Optimized image loading across high-res fashion galleries by implementing lazy-loading, WebP assets, and responsive srcset attributes."}]'::jsonb,
    'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80',
    '[{"title":"Homepage Hero & Featured Collection","url":"https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80","caption":"Hero section showcasing seasonal lookbook and instant shop CTA."},{"title":"Product Detail View & Variant Selector","url":"https://images.unsplash.com/photo-1479064555552-3ef4979f8908?auto=format&fit=crop&w=800&q=80","caption":"Interactive variant picker with real-time inventory indicator."},{"title":"Mobile Shopping View","url":"https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=800&q=80","caption":"Mobile drawer navigation and touch-optimized checkout funnel."}]'::jsonb,
    'https://example.com/aura-apparel',
    true,
    array['Pixel-perfect responsive layout across all device screens', 'Custom Shopify Liquid code built for easy store merchant updates', 'Sub-2 second mobile page load performance', 'Streamlined checkout conversion UX'],
    1
  ),
  (
    'proj-2',
    'Vanguard Corporate WordPress',
    'vanguard-corporate-wordpress',
    'WORDPRESS',
    'WordPress',
    array['WordPress', 'Elementor Pro', 'Custom CSS', 'Loop Build', 'PHP'],
    'Professional business website with custom layouts, responsive sections, dynamic loop grids, and optimized content presentation.',
    'A high-performing corporate WordPress portal crafted with Elementor Pro and custom PHP loop queries. Designed to showcase company services, case studies, team profiles, and investor relations with custom post types and dynamic templates.',
    'WordPress Developer',
    array['Elementor Pro custom single & archive template builds', 'Custom Post Types & Taxonomy loop grids', 'Custom CSS styling for tailored corporate identity', 'On-page SEO optimization & metadata schema', 'Interactive service calculator & inquiry form modal', 'Cross-browser tested & WCAG accessibility compliant'],
    '[{"title":"Project Goal","content":"Establish an authoritative web presence with dynamic content publishing capabilities for non-technical team members."},{"title":"Design Direction","content":"Clean corporate structure with sharp typography, micro-interactions, and visual proof metrics."},{"title":"Technical Execution","content":"Leveraged Elementor Pro''s Loop Grid builder combined with custom hooks in functions.php to maintain light database query footprints."}]'::jsonb,
    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    '[{"title":"Executive Homepage Overview","url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80","caption":"Hero section highlighting core enterprise verticals."},{"title":"Service Portfolio & Loop Grid","url":"https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80","caption":"Dynamic post grid filtered by industry category."}]'::jsonb,
    'https://example.com/vanguard-corp',
    true,
    array['Custom WordPress Loop Builder integration', 'Enhanced user navigation architecture', 'Fully editable CMS dashboard for client staff'],
    2
  ),
  (
    'proj-3',
    'Nova Analytics React Dashboard',
    'nova-analytics-react-dashboard',
    'REACT',
    'React / Web App',
    array['React.js', 'TailwindCSS', 'JavaScript ES6+', 'GSAP'],
    'Responsive dashboard interface demonstrating component-based UI development, data visualization, and interactive state management.',
    'A modern, single-page analytics web application built using React.js and TailwindCSS. Features modular component architecture, dark/light theme switching, filterable data tables, and animated KPI metrics built with GSAP.',
    'Front-End Developer',
    array['React.js component-driven frontend architecture', 'TailwindCSS utility styling & theme provider', 'GSAP smooth micro-animations for data metrics', 'Filterable data grids & search logic', 'Responsive navigation drawer for desktop & mobile'],
    '[{"title":"Project Goal","content":"Provide business operators with a clean, fast interface to digest key revenue metrics and real-time operational data."},{"title":"Technical Stack","content":"React 19 Hooks for local state management, TailwindCSS for layout, and GSAP for state transition animations."}]'::jsonb,
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    '[{"title":"Main Control Center & KPI Cards","url":"https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80","caption":"Real-time statistics dashboard with interactive metrics."},{"title":"Filterable Data Table View","url":"https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80","caption":"Searchable data table with paginated control."}]'::jsonb,
    'https://example.com/nova-analytics',
    true,
    array['Modular reusable React component library', 'Smooth GSAP data entry animations', 'Fast client-side rendering & state management'],
    3
  ),
  (
    'proj-4',
    'Lumina Custom GemPages Shopify Theme',
    'lumina-custom-gempages-shopify-theme',
    'SHOPIFY',
    'Shopify',
    array['Shopify', 'GemPages', 'Custom Shopify Code', 'Liquid', 'CSS3'],
    'High-converting Shopify cosmetics brand storefront built with custom GemPages templates and customized Liquid snippets.',
    'A tailored Shopify store for a premium cosmetics brand. Features custom GemPages layout templates, interactive ingredient highlight accordion, custom bundle builder, and optimized mobile drawer cart.',
    'Shopify Developer',
    array['GemPages drag-and-drop customized layouts', 'Custom Shopify Liquid code extensions', 'Interactive Product Bundle & Upsell widget', 'Custom CSS styling matching brand design guidelines', 'Customer reviews & photo user-generated content integration'],
    '[{"title":"Project Goal","content":"Create a visually captivating e-commerce experience highlighting product purity and customer testimonials."},{"title":"Development Strategy","content":"Combined GemPages for rapid page layout iterations with custom Liquid snippets for store logic."}]'::jsonb,
    'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1200&q=80',
    '[{"title":"Storefront & Beauty Collection","url":"https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80","caption":"Custom promotional hero banner with shop now CTA."}]'::jsonb,
    'https://example.com/lumina-beauty',
    false,
    array['Custom Shopify bundle builder workflow', 'Optimized mobile buyer journey', 'High aesthetic standards matching beauty industry benchmarks'],
    4
  ),
  (
    'proj-5',
    'UrbanTech WooCommerce Store',
    'urbantech-woocommerce-store',
    'E-COMMERCE',
    'WordPress / WooCommerce',
    array['WordPress', 'WooCommerce', 'Elementor Pro', 'Custom CSS', 'PHP'],
    'Electronics & gadget e-commerce platform with customized product filters, payment gateway integration, and customer dashboard.',
    'A feature-packed WooCommerce store for consumer electronics. Features multi-currency switcher, custom product attribute filters, AJAX search with instant suggestions, and customized customer account portal.',
    'WordPress & WooCommerce Developer',
    array['WooCommerce catalog & checkout customization', 'Elementor Pro single product & category shop templates', 'Custom PHP hooks for checkout field customization', 'AJAX live search with auto-complete product cards', 'Speed optimized with caching and WebP asset conversion'],
    '[{"title":"Project Goal","content":"Build a scalable tech e-commerce store capable of cataloging 500+ product SKUs with instant search and filtering."}]'::jsonb,
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80',
    '[{"title":"Shop Catalog & Tech Categories","url":"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80","caption":"Product catalog grid with dynamic specs filtering."}]'::jsonb,
    'https://example.com/urbantech-store',
    false,
    array['Streamlined multi-category e-commerce navigation', 'Customized WooCommerce checkout experience', 'Scalable CMS database configuration'],
    5
  ),
  (
    'proj-6',
    'Kinetic Interactive Web Experience',
    'kinetic-interactive-web-experience',
    'CUSTOM DEVELOPMENT',
    'Front-End',
    array['HTML5', 'CSS3', 'JavaScript ES6+', 'GSAP', 'TailwindCSS'],
    'High-impact agency landing page featuring custom GSAP scroll-triggered animations, interactive SVG graphics, and responsive design.',
    'A creative web experience showcasing modern front-end capabilities. Built with raw HTML5/CSS3, TailwindCSS, vanilla JS ES6+, and GSAP timeline animations for scroll-based storytelling and micro-interactions.',
    'Front-End Developer',
    array['GSAP ScrollTrigger timeline animations', 'Custom cursor & magnetic button hover effects', 'Modular JS structure without heavy framework overhead', 'Pixel-perfect responsive layout across display breakpoints'],
    '[{"title":"Project Goal","content":"Demonstrate high-end visual interaction craftsmanship with smooth 60fps animations."}]'::jsonb,
    'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
    '[{"title":"Interactive Showcase View","url":"https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80","caption":"Scroll-triggered animation stage with retro badges."}]'::jsonb,
    'https://example.com/kinetic-web',
    true,
    array['Ultra-smooth 60fps GSAP scroll animations', 'Zero-framework lightweight performance', 'Creative retro digital interaction design'],
    6
  ),
  (
    'proj-7',
    'Kroma Creative Studio Portfolio',
    'kroma-creative-studio-portfolio',
    'UI/UX DESIGN',
    'UI/UX & Web Design',
    array['Figma', 'UI/UX Design', 'Wireframing', 'TailwindCSS', 'React'],
    'Interactive digital studio brand identity, design system, and pixel-perfect UI/UX design prototype.',
    'A comprehensive UI/UX design project for a modern creative agency. Includes modular design tokens, interactive Figma prototypes, responsive grid structures, and dark/light design systems tailored for creative professionals.',
    'Lead UI/UX & Web Designer',
    array['Figma design system & component library', 'Pixel-perfect responsive desktop & mobile artboards', 'Interactive micro-interaction prototype states', 'Design token mapping for seamless front-end handoff'],
    '[{"title":"UX Strategy","content":"Established bold typography scale and intuitive navigation structure to highlight studio deliverables with zero friction."}]'::jsonb,
    'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    '[{"title":"UI Design System","url":"https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80","caption":"Figma design tokens and typography hierarchy."}]'::jsonb,
    'https://example.com/kroma-studio',
    true,
    array['Pixel-perfect UI design system', 'Seamless front-end component handoff'],
    7
  ),
  (
    'proj-8',
    'Solstice Multi-Vendor Marketplace',
    'solstice-multivendor-marketplace',
    'E-COMMERCE',
    'E-Commerce / Next.js',
    array['Next.js', 'Stripe', 'E-Commerce', 'TailwindCSS', 'Node.js'],
    'Scalable headless multi-vendor e-commerce marketplace with real-time search, vendor dashboards, and custom checkout.',
    'Full-scale e-commerce marketplace platform connecting artisan vendors with global buyers. Features instant Algolia-powered search, automated Stripe Connect payout splits, custom seller dashboards, and high-conversion product pages.',
    'Full-Stack E-Commerce Developer',
    array['Next.js App Router server-side rendered storefront', 'Stripe Connect multi-vendor automated payment routing', 'Real-time product filtering & instant search', 'Vendor catalog management & revenue analytics'],
    '[{"title":"Architecture","content":"Decoupled headless storefront using Next.js for sub-second page loads and dynamic checkout scaling."}]'::jsonb,
    'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=1200&q=80',
    '[{"title":"Marketplace Storefront","url":"https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80","caption":"Multi-vendor catalog view and instant category filter."}]'::jsonb,
    'https://example.com/solstice-market',
    true,
    array['Sub-second page load performance', 'Seamless multi-vendor Stripe Connect payouts'],
    8
  ),
  (
    'proj-9',
    'Veloce High-Performance SaaS Web App',
    'veloce-saas-web-app',
    'REACT/Next.js Front-End',
    'React / Web App',
    array['React', 'Next.js', 'TypeScript', 'TailwindCSS', 'GSAP'],
    'Lightning-fast SaaS platform marketing site built with Next.js App Router, TypeScript, and GSAP animations.',
    'A modern SaaS marketing landing page engineered for high conversion rates. Features smooth scroll-driven GSAP animations, interactive pricing calculators, light/dark theme toggling, and clean TypeScript component architecture.',
    'Front-End Developer',
    array['Next.js SSG prerendering with TypeScript safety', 'Interactive tier pricing toggle calculator', 'GSAP timeline scroll-triggered feature reveals', '100/100 Lighthouse performance score optimization'],
    '[{"title":"Performance Focus","content":"Achieved perfect 100/100 Google Lighthouse scores by optimizing font loading and bundle sizes."}]'::jsonb,
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    '[{"title":"SaaS Dashboard Hero","url":"https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80","caption":"Hero section with animated dashboard metric preview."}]'::jsonb,
    'https://example.com/veloce-saas',
    true,
    array['100/100 Lighthouse performance rating', 'Interactive pricing calculator UI'],
    9
  ),
  (
    'proj-10',
    'Nexus Enterprise Headless CMS Portal',
    'nexus-enterprise-cms-portal',
    'CUSTOM DEVELOPMENT',
    'Custom Development',
    array['Node.js', 'Express.js', 'REST API', 'MongoDB', 'TailwindCSS'],
    'Custom REST API management dashboard and decoupled headless CMS backend for corporate content publishing.',
    'Custom enterprise portal built to manage multi-channel digital content publishing via RESTful APIs. Includes role-based access control (RBAC), media manager with Cloudinary integration, and live API documentation.',
    'Full-Stack Custom Developer',
    array['Custom Node.js & Express.js REST API server', 'Role-based authorization & JWT security', 'Decoupled React management console', 'MongoDB database indexing & schema validation'],
    '[{"title":"API Design","content":"Designed clean REST endpoints with robust validation middleware to serve content securely."}]'::jsonb,
    'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    '[{"title":"CMS Control Center","url":"https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80","caption":"API key management & analytics dashboard view."}]'::jsonb,
    'https://example.com/nexus-portal',
    true,
    array['Secure JWT & RBAC access control', 'Decoupled headless content delivery'],
    10
  )
on conflict (id) do update set
  title = excluded.title,
  slug = excluded.slug,
  category = excluded.category,
  platform = excluded.platform,
  technologies = excluded.technologies,
  short_description = excluded.short_description,
  description = excluded.description,
  role = excluded.role,
  features = excluded.features,
  brainstorming = excluded.brainstorming,
  hero_image = excluded.hero_image,
  gallery = excluded.gallery,
  live_url = excluded.live_url,
  featured = excluded.featured,
  results_highlights = excluded.results_highlights,
  order_index = excluded.order_index;
