-- ==============================================================================
-- 02. SEED PROFILE CONTENT (Metrics, Services, Workflow, Featured Showcase, Skills)
-- ==============================================================================

-- 1. Seed Metrics
insert into public.metrics (value, label, tags, order_index) values
('3+ YEARS', 'PROFESSIONAL EXPERIENCE', array['Fiverr', 'Upwork', 'Direct Agency'], 1),
('50+', 'WEBSITES DEV', array['Fashion', 'Accessories', 'Real Estate', 'E-Commerce'], 2),
('eCommerce', 'DEVELOPMENT CAPABILITY', array['Shopify', 'WooCommerce', 'Amazon'], 3),
('GLOBAL', 'CLIENT COLLABORATION', array['UK', 'USA', 'Germany', 'Canada'], 4)
on conflict do nothing;

-- 2. Seed Services / Expertise
insert into public.services (num, title, icon_name, scope, skills, pills, order_index) values
('01', 'SHOPIFY & ECOMMERCE ENGINEERING', 'ShoppingBag', 'Building high-converting eCommerce experiences with custom Shopify themes, advanced Liquid development, storefront integrations, and tailored shopping functionality.', array['Custom Shopify Theme & Liquid Section Development', 'Storefront API, Custom Apps & Webhook Integrations', 'Advanced Product Variants, Pricing & Cart Logic', 'Custom Storefront Features & Third-Party Integrations', 'Conversion-Focused Product Pages & Checkout UX'], array['Shopify', 'Liquid', 'StorefrontAPI', 'CustomApps', 'Ecommerce'], 1),
('02', 'CUSTOM APPLICATIONS & API DEVELOPMENT', 'Code2', 'Developing tailored web applications and business tools using modern frontend frameworks, scalable backend architecture, and database-driven functionality.', array['React.js & Next.js Application Development', 'Node.js, Express.js & REST API Engineering', 'MongoDB & MySQL Database Integration', 'Custom Dashboards, Admin Panels & CRUD Systems', 'Third-Party API Integration, Authentication & Automation'], array['React', 'NextJS', 'NodeJS', 'MongoDB', 'APIIntegration'], 2),
('03', 'FRONTEND ENGINEERING, UI/UX & PROTOTYPING', 'Layout', 'Transforming ideas and design concepts into responsive, interactive interfaces through modern frontend engineering, rapid prototyping, and polished user experiences.', array['Responsive UI Development with React.js & Next.js', 'Interactive Prototypes & Functional MVP Development', 'Custom HTML, CSS, JavaScript & Component Systems', 'GSAP Animations, Scroll Interactions & Micro-Interactions', 'Performance Optimization, Accessibility & Core Web Vitals'], array['FrontendDevelopment', 'UIUX', 'Prototyping', 'GSAP', 'ResponsiveDesign'], 3),
('04', 'ECOMMERCE MARKETING & WORKFLOW AUTOMATION', 'Zap', 'Connecting eCommerce platforms with analytics, marketing tools, and automated workflows to streamline operations, improve customer engagement, and support business growth.', array['Klaviyo Email Marketing & Automated Customer Journeys', 'Marketing API Integrations & Workflow Automation', 'Google Analytics 4 & Conversion Tracking', 'Meta Pixel, Event Tracking & Marketing Attribution', 'Conversion Rate Optimization (CRO) & Technical SEO', 'Lead Capture, CRM Integration & Automated Notifications'], array['MarketingAutomation', 'Klaviyo', 'GA4', 'CRO', 'MetaPixel', 'WorkflowAutomation'], 4)
on conflict do nothing;

-- 3. Seed Workflow
insert into public.workflow (id, step_id, step_label, tab_title, tagline, description, deliverables, timeline, milestone, order_index) values
('step-1', '01', 'STEP 01', 'Research & Wireframing', 'Uncovering user needs & establishing structural blueprints', 'Deep-dive discovery call, competitive benchmarking, user journey mapping, and low-fidelity wireframing to lock down layout architecture, conversion funnels, and sitemap before any visual design begins.', array['User Persona & Journey Mapping', 'Interactive Low-Fi Layout Wireframes', 'Information Architecture & Sitemap', 'Shopify / WordPress Feature Scope Audit'], '3-5 Days', 'Interactive Wireframe Approval', 1),
('step-2', '02', 'STEP 02', 'High-Fidelity Figma UI', 'Crafting pixel-perfect, responsive visual design systems', 'Creating modern, conversion-focused high-fidelity Figma prototypes following your brand guidelines. Establishing typography, color tokens, interactive components, PageFly/GemPages wireframes, and mobile-first layouts.', array['Pixel-Perfect Desktop & Mobile UI Designs', 'Interactive Figma Prototype & Micro-Animations', 'Reusable UI Component & Style Design System', 'PageFly & GemPages Custom Section Blueprints'], '4-6 Days', 'Figma Visual Design Sign-off', 2),
('step-3', '03', 'STEP 03', 'Custom WP & Shopify Build', 'Building responsive, standards-compliant custom code', 'Transforming approved designs into clean, responsive storefronts using custom Shopify Liquid, PageFly/GemPages sections, WordPress Elementor Pro Loop Builders, React.js UI modules, and custom CSS overrides.', array['Custom Shopify Liquid Theme Sections', 'Elementor Pro & Dynamic Loop Builder Setup', 'Fast AJAX Side-Cart Drawer & Variant Selectors', 'Clean HTML5 / CSS3 / ES6+ Component Integration'], '5-10 Days', 'Staging Site Build Review', 3),
('step-4', '04', 'STEP 04', 'Speed Optimization & Launch', 'Fine-tuning performance, cross-browser QA, and live deployment', 'Running Core Web Vitals optimization, image compression pipelines, cross-browser QA on staging, DNS/SSL setup, and final client walkthrough before going live with handover documentation.', array['Google PageSpeed & Core Web Vitals Optimization', 'Cross-Browser & Multi-Device QA Testing', 'Launch Checklist & DNS / SSL Configuration', 'Client Walkthrough Video & Handover Docs'], '2-4 Days', 'Production Site Launch', 4)
on conflict do nothing;

-- 4. Seed Featured Projects (Showcase Ticker Rows)
insert into public.featured_projects (row_number, title, category, tech_stack, description, client, year, images, order_index) values
(1, 'Luxury Fashion E-Commerce', 'Shopify', array['Shopify', 'Liquid', 'JavaScript', 'GSAP'], 'High-converting fashion storefront with custom Liquid code, instant cart drawer, and lookbook grid.', 'Aura Apparel Global', '2026', array['https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=1200&q=80'], 1),
(1, 'Employee Management System', 'MERN', array['React', 'Node.js', 'Express', 'MongoDB'], 'Enterprise portal featuring automated payroll processing, employee metrics, and shift scheduling.', 'Nexus Enterprise Systems', '2026', array['https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=1200&q=80'], 2),
(1, 'Creative Agency Digital Hub', 'Web Development', array['React', 'GSAP', 'Lenis', 'TailwindCSS'], 'Interactive agency landing page with 3D webgl canvas, smooth momentum scroll, and cursor effects.', 'Kroma Creative Studio', '2026', array['https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?auto=format&fit=crop&w=1200&q=80'], 3),
(1, 'Modern SaaS Analytics Dashboard', 'SaaS', array['React', 'Node.js', 'TailwindCSS', 'Chart.js'], 'Real-time analytics portal with automated telemetry tracking, user cohorts, and report export.', 'Veloce Technologies', '2025', array['https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=1200&q=80'], 4),
(1, 'Corporate Business WordPress Site', 'WordPress', array['WordPress', 'Elementor Pro', 'Custom CSS', 'PHP'], 'Corporate portal featuring custom post types, dynamic archive loop grids, and SEO optimization.', 'Vanguard Global Group', '2025', array['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1542744801-30d00f050a69?auto=format&fit=crop&w=1200&q=80'], 5),
(2, 'Multi-Vendor E-Commerce Platform', 'E-Commerce', array['Next.js', 'Shopify', 'TailwindCSS', 'Node.js'], 'Scalable marketplace with merchant onboarding, payout processing, and multi-currency checkout.', 'Solstice Digital Merchants', '2026', array['https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1556742049-0a67daf40955?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1556740758-90de374c12ad?auto=format&fit=crop&w=1200&q=80'], 1),
(2, 'Minimalist Watch & Goods Store', 'Shopify', array['Shopify', 'PageFly', 'Liquid', 'JavaScript'], 'Bespoke watch storefront with 360-degree product viewer, custom filter drawer, and mobile funnel.', 'Chronos Timepieces Ltd', '2025', array['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80'], 2),
(2, 'Gourmet Culinary & Dining Web App', 'Web Development', array['React', 'Express', 'TailwindCSS', 'GSAP'], 'Interactive dining experience page featuring table reservation booking, order tracking, and chef recipes.', 'L''Etoile Culinary Group', '2026', array['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=80'], 3),
(2, 'Fitness & Wellness Community Portal', 'MERN', array['React', 'Node.js', 'MongoDB', 'Express'], 'Subscription fitness application with live workout streams, personal trainer scheduling, and goal tracking.', 'Pulse Athletic Club', '2026', array['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=80'], 4),
(2, 'Architectural Portfolio & Studio', 'WordPress', array['WordPress', 'Custom Theme', 'GSAP', 'Custom CSS'], 'High-end architectural showcase featuring full-screen project sliders, blueprint downloads, and interactive maps.', 'Modus Architecture Studio', '2025', array['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80'], 5)
on conflict do nothing;
